runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  OPENAI_API_KEY: "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"

handlers:
- url: /.*
  script: auto
